name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> ${GITHUB_ENV}
          echo "${GITHUB_REF/refs\/tags\//}"
          echo "${GITHUB_REF#refs/*/}"
          echo "${GITHUB_REF}"
      - uses: actions/checkout@v4

      - name: set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-node@v4

      - name: Build FE
        run: |
          echo "$(git show -s --format=%H)"
          echo "GITHASH=$(git show -s --format=%H)" >> ${GITHUB_ENV}
          make build_fe

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VERSION=${{ env.VERSION }}
            GITHASH=${{ env.GITHASH }}
          context: .
          file: ./DockerfileGithubAction
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_LC }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_LC }}:latest
