name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
        
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.2.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.6.1
    
    - name: Build FE
      uses: cristi-mb/build-fe@1.3
        
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
